### ISSUE TITLE
2.1.1 Limit sell order error

### ISSUE THREAD

**Issue by crlsnr** [tony-ho/binance-oco#9]
When placing an order with only sell limit orders and stop limit orders the command line values do not translate to a proper exchange API call.  For example, I attempted to set a sell limit order of a coin for a price at $86.2 but the exchange received a price of $8.92 instead.  Fortunately the exchange rejected the order.  

Is it possible that the recent logic that was added for trades that started with a buy order messed up the stop limit order logic?

**Comment by tony-ho** [comment]
@crlsnr v2.0.0 introduced a change to set the default limit for stop limit orders to emulate stop market orders.

If specific buy/sell limit prices aren't specified with the `-l` or `-B/-E` options respectively, the tool calculates limits as follows:
- Buy limit set to maximum allowed by available balance and Binance PERCENT_PRICE trading rule
- Sell limit set to minimum allowed by Binance MIN_NOTIONAL and PERCENT_PRICE trading rules

For further details, see the Binance Trading Rules here: https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule

Note: Binance will still fill your orders at the best price available, but orders may show a much lower sell or much higher buy price.

Previously, limit prices on stop-limit orders were set to the stop price by default. This created a risk of orders not being filled if the price skipped past the limit price quickly.

To make the tool behave as it did prior to v2.0.0, set the `-l` or `-B/-E` options to the same value as the `-s` and `-b/-e` options respectively.

The exchange rejecting the order sounds like unexpected behaviour. Can you provide details of the command line options you used and the log output so that I can investigate?

**Comment by tony-ho** [comment]
Closing as default limit prices are as designed.

The issue with rejected stop orders should be addressed in v2.2.0.
